### PR TITLE
Make address optional in decoding, for BIP72 urls

### PR DESCRIPTION
**Pull request by afk11**
What do you think of supporting BIP72 in this library?

There are two parts to dealing with it 
 * backwards compatible setting the address/value, in addition to the `r` parameter.
 * non-compatible form lacking the address (details specified in the payment request)

I could maybe move it to a different function intending to support both if the changes would interact undesirably with existing usage.

### CODE REVIEW

**Comment by dcousens** [comment]
I don't think `BIP21` makes sense without an address.
Otherwise,  this is simply a URI no?
But I understand the likeness... maybe `bip21/extensions` and `.bip72`?

**Comment by afk11** [comment]
Yeah the library name is quite specific about which spec it implements :) yea putting the decode function in an extension module might work. don't think any new code is required for encoding them, it just works..

**Comment by dcousens** [comment]
@afk11 close or continue?

**Comment by afk11** [comment]
Closed

**Pull request closed without merging**
